name: 'setup-sqlpackage'
description: 'Helps set up SqlPackage into PATH for later usage.'
author: 'Microsoft, Corey Webber'
branding:
  color: purple
  icon: terminal
inputs:
  vswhere-path:
    required: false
    description: 'Folder location of where vswhere.exe is located if a self-hosted agent'
  sql-version:
    description: 'Version of SQL Server to search; defaults to latest if not specified'
    required: false
outputs:
  sqlpackagePath:
    description: 'The resulting location of sqlpackage for your inputs'

runs:
  using: 'node12'
  main: 'dist/index.js'
